const floorDetails = [
  {
    floor: "1st Floor",
    theme: "Starting Plains",
    about:
      "The largest floor in Aincrad, spanning 80 square kilometers. It serves as the starting point for all players.",
    settlements: [
      "Town of Beginnings",
      "Tolbana",
      "Horunka Village",
      "Medai Village",
    ],
    quests: ["Cows' Counter Attack", "Secret Medicine of the Forest"],
    bosses: ["Illfang the Kobold Lord", "The Fatal Scythe"],
    monsters: [
      "Frenzy Boar",
      "Little Nepents",
      "Large Nepents",
      "Ruin Kobold Troopers",
      "Ruin Kobold Sentinels",
      "Scavenger Toads",
      "Dire Wolf",
    ],
    gallery: {
      "Town of Beginnings": "/images/image1.webp",
      "West Field": "/images/west-fields.webp",
      Tolbana: "/images/Tolbana.webp",
      Forest: "/images/first-forest.webp",
      Map: "/images/floor1-map.webp",
    },
  },
  {
    floor: "2nd Floor",
    theme: "Savanna and Plains",
    about:
      "A savanna realm covered in plains and boulders, similar in size to the 1st Floor.",
    settlements: [
      "Urbus",
      "Marome",
      "Martial Arts Master's Hut",
      "First Floor Dungeon Exit",
    ],
    quests: ["Martial Arts Extra Skill Quest"],
    bosses: [
      "Bullbous Bow",
      "Nato the Colonel Taurus",
      "Baran the General Taurus",
      "Asterius the Taurus King",
    ],
    monsters: [
      "Jagged Worm",
      "Lesser Taurus Striker",
      "Red Spotted Beetle",
      "Storm Hornet",
      "Taurus Ironguard",
      "Taurus Ringhurler",
      "Trembling Cow",
      "Trembling Ox",
      "Windwasp",
    ],
    gallery: {
      Panorama: "/floorTwo/image1.webp",
      Urbus: "/floorTwo/image2.webp",
      "Boss Den": "/floorTwo/image3.webp",
      Taran: "/floorTwo/image4.webp",
      Labyrinth: "/floorTwo/image5.webp",
    },
  },
  {
    floor: "3rd Floor",
    theme: "Forest",
    about: "A forest-themed floor featuring dense woods and elven conflicts.",
    settlements: [
      "Zumfut",
      "Dark Elf and Forest Elf Bases",
      "Forest Elf Camp",
      "Queen Spider's Nest",
      "Spirit Trees (Western and Eastern)",
      "Dessel",
    ],
    quests: [
      "Guild Formation Quest",
      "First Ten Chapters of the Elf War Campaign",
      "Pet-finding Quest",
    ],
    bosses: [
      "Fallen Elf Commander",
      "Nephila Regina",
      "Unnamed Giant Spider",
      "The Indolent Treant",
      "Nerius the Evil Treant",
    ],
    monsters: [
      "Coppice Spider",
      "Dark Elven Wolf Handler",
      "Elder Treant",
      "Elder Sapling",
      "Fallen Elf Warrior",
      "Forest Elven Falconer",
      "Roaring Wolf",
      "Thicket Spider",
      "Treant Sapling",
    ],
    gallery: {
      Map: "/floorThree/image1.webp",
      Forest: "/floorThree/image2.webp",
      "Dark Elf Base": "/floorThree/image3.webp",
      "Spider Nest": "/floorThree/image4.webp",
      "Spirit Tree": "/floorThree/image6.webp",
      "Elf Camp Wall": "/floorThree/image5.webp",
    },
  },
  {
    floor: "4th Floor",
    theme: "Waterways and Forests",
    about:
      "Originally a desert canyon in the beta version, transformed into a waterway-themed floor in the official release.",
    settlements: [
      "Rovia",
      "Bear Forest",
      "Fallen Elf Hideout",
      "Caldera Lake",
      "Usco Village",
      "Forest Elf Castle",
      "Yofel Castle",
    ],
    quests: [
      "Laketop Fortress",
      "Elf War Campaign Quests",
      "Shipwright of Yore",
    ],
    bosses: ["Biceps Archelon", "Wythege the Hippocampus"],
    monsters: [
      "Dark Elven Gatekeeper",
      "Fallen Elven Foreman",
      "Fallen Elven Guard",
      "Forest Elven Heavy Warrior",
      "Forest Elven Inferior Knight",
      "Forest Elven Light Warrior",
      "Forest Elven Rower",
      "Forest Elven Spearman",
      "Forest Elven Swordsman",
      "Gaudy Nepenthes",
      "Magnatherium",
      "Scuttle Crab",
    ],
    gallery: {},
  },
  {
    floor: "8th Floor",
    theme: "Unknown",
    about:
      "Minimal info available. Featured in one side story where Kirito and Asuna use teleport crystals.",
    settlements: [],
    quests: [],
    bosses: [],
    monsters: [],
    gallery: {},
  },
];
export default floorDetails;
